name: CI

on:
  push:
  pull_request:

env:
  CI: true

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install -g pnpm
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm build