name: Main Commit Checks
on: [push]

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                # The node version, you can put one or many versions in here to test with
                node: [18.20.3]
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            # Cache node modules
            - name: cache modules
              uses: actions/cache@v2
              with:
                  path: app/node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('app/pnpm-lock.yaml') }}

            - run: sudo npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --fetch-timeout  1000000
              env:
                  CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
              working-directory: ./app

            - name: Verify directory
              run: |
                  cd app
                  echo "Current directory: $(pwd)"
                  ls -la

            # - name: Linting
            #   run: pnpm run lint
            #   working-directory: ./app

            # - name: Jest run
            #   run: pnpm test
            #   working-directory: ./app

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  working-directory: ./app
                  start: pnpm serve --mode e2e
                  wait-on: 'http://localhost:5000/'
                  wait-on-timeout: 180
                  browser: chrome
                  headless: true
              env:
                  USE_HTTP: true

            # Extract screenshots to git if tests fail
            - name: Extract screenshots to git
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: app/cypress/screenshots

            # Always extract videos to git
            - name: Extract videos to git
              uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: cypress-videos
                  path: app/cypress/videos
